import numpy as np

#Different parameters for the project
g = 9.81 #m/s^2
nu = 1e-6 #m^2/s (kinematic viscosity of water)
mu = 1e-3 #kg/(m*s) (dynamic viscosity of water)
rho_p = 2500 #kg/m^3 (density of particles)
m_0 = 0.001 #kg (mass of the released particles)
R_cyl = 4.9e-2/2 #m (radius of the cylinder)
r_p = 90e-6 #m (radius of particles)
H_cyl = 0.027 #m (height of the cylinder)
R_Landeau = ((3/4)* R_cyl**2 * H_cyl)**(1/3)
a2_Landeau = 0.52*(1-0.07)
a3_Landeau = 0.52*0.07

rho_released = 998.7 #kg/m^3 (density of the released fluid)
rho_infinity = 998.7 #kg/m^3 (density of the fluid in the tank)

phi = (m_0/rho_p)/(np.pi * R_cyl**2 * H_cyl) #particle volume fraction 

rho_clouds = phi*rho_p + (1-phi)*rho_released #density of the particle cloud
w_stokes = (2/9)*((rho_p - rho_released)*g*r_p**2)/mu #Stokes settling velocity of the particles
U_vortex = np.sqrt(a2_Landeau*(rho_clouds-rho_infinity)/rho_clouds*g*R_Landeau + a3_Landeau*g*R_Landeau) #velocity scale of the vortex ring generated by the released cloud, buoyancy and inertia effects are considered

#Dimensionless numbers
Re_p = w_stokes*2*r_p/nu #Reynolds number of the particles
formation_number = H_cyl/(2*R_cyl) #formation number of the released cloud

w_s = w_stokes/(1+0.15*Re_p**0.687) #Settling velocity of the particles considering the effect of Reynolds number
Rouse_number = w_s/(U_vortex) #Rouse number of the released cloud

# 1 pixel = 0.267112299e-2 m in the experiments
# 1pixel = 1/50 s

def compute_u_vortex_exp(pixel_vertical, pixel_temps):
	"""Compute U_vortex from experimental data."""
	# Implementation for experimental computation
	return pixel_vertical * 0.267112299e-3 / (pixel_temps / 50)

print(f"Computed U_vortex from experimental data: {compute_u_vortex_exp(101, 9):.6f} m/s")
print(f"Computed U_vortex from experimental data: {compute_u_vortex_exp(104, 6):.6f} m/s")


V_f = np.array([10e-3,20e-3,30e-3,40e-3,50e-3]) #m^3 (volume of the released fluid) 
H_cyl = ((m_0/rho_p) + V_f) / (np.pi * R_cyl**2)
print(f"Computed H_cyl for different V_f: {H_cyl}") 
